const categories = [
  ['💻','برمجة وتطوير'],['🎨','تصميم وإبداع'],['📣','تسويق وإعلانات'],['📷','تصوير وفيديو'],['📝','كتابة وترجمة'],['🔧','خدمات محلية']
];
const services = [
  {name:'تصميم هوية بصرية احترافية',user:'محمد — الجزائر',rating:'4.9',price:'ابتداءً من 8,000 دج',tag:'تصميم'},
  {name:'إنشاء متجر إلكتروني متكامل',user:'أحمد — وهران',rating:'5.0',price:'ابتداءً من 35,000 دج',tag:'برمجة'},
  {name:'إدارة صفحات Facebook و Instagram',user:'سارة — الجزائر العاصمة',rating:'4.8',price:'ابتداءً من 12,000 دج / شهر',tag:'تسويق'}
];

export default function Home(){return <>
  <div className="topbar"><div className="container">🇩🇿 منصة جزائرية للخدمات والسلع — تعامل بثقة داخل الجزائر</div></div>
  <header className="nav"><div className="container navin"><div className="logo">سوق <span>DZ</span></div><nav className="links"><a href="#services">الخدمات</a><a href="#projects">المشاريع</a><a href="#products">السلع</a><a href="#how">كيف تعمل؟</a></nav><div className="actions"><button className="btn">دخول</button><button className="btn primary">إنشاء حساب</button></div></div></header>
  <main>
    <section className="hero"><div className="container heroGrid"><div><span className="eyebrow">السوق الرقمي الجزائري الجديد</span><h1>أنجز أعمالك مع <span>أفضل المواهب</span> في الجزائر</h1><p>ابحث عن مستقل، اطلب خدمة، اشترِ منتجًا أو انشر مشروعك. منصة واحدة تربط العملاء بالمحترفين والبائعين في كل الولايات.</p><div className="search"><input placeholder="ماذا تبحث عنه؟ مثال: تصميم شعار، برمجة موقع..."/><button>بحث 🔎</button></div></div><div className="heroCard"><strong>🔥 خدمات رائجة الآن</strong><div className="mini"><strong>تصميم منشورات سوشيال ميديا</strong><span className="price">ابتداءً من 3,000 دج</span></div><div className="mini"><strong>تصوير منتجات احترافي</strong><span className="price">ابتداءً من 5,000 دج</span></div><div className="mini"><strong>إنشاء موقع شركة</strong><span className="price">ابتداءً من 25,000 دج</span></div></div></div></section>
    <section className="section"><div className="container"><div className="sectionHead"><div><h2>استكشف حسب الفئة</h2><p className="muted">كل ما تحتاجه من محترفين جزائريين</p></div></div><div className="categories">{categories.map(([icon,name])=><div className="cat" key={name}><div className="icon">{icon}</div>{name}</div>)}</div></div></section>
    <section className="section" id="services"><div className="container"><div className="sectionHead"><div><h2>خدمات مميزة</h2><p className="muted">محترفون موثوقون وأسعار واضحة بالدينار الجزائري</p></div><button className="btn">عرض الكل ←</button></div><div className="cards">{services.map(s=><article className="card" key={s.name}><div className="cardTop"><div className="avatar">{s.user[0]}</div><div><strong>{s.user}</strong><div className="rating">★ {s.rating} · موثوق</div></div></div><h3>{s.name}</h3><span className="price">{s.price}</span><div className="tags"><span className="tag">{s.tag}</span><span className="tag">تسليم سريع</span></div></article>)}</div></div></section>
    <section className="section" id="how"><div className="container"><div className="sectionHead"><div><h2>كيف تعمل المنصة؟</h2><p className="muted">تجربة بسيطة من الطلب إلى التسليم</p></div></div><div className="trust"><div className="trustBox"><div className="icon">1️⃣</div><h3>انشر أو ابحث</h3><p className="muted">انشر مشروعك أو اختر خدمة جاهزة أو منتجًا.</p></div><div className="trustBox"><div className="icon">2️⃣</div><h3>تواصل واتفق</h3><p className="muted">قارن العروض وتحدث مع مقدم الخدمة داخل المنصة.</p></div><div className="trustBox"><div className="icon">3️⃣</div><h3>أنجز وقيّم</h3><p className="muted">استلم طلبك، ثم قيّم التجربة لبناء سوق أكثر ثقة.</p></div></div></div></section>
    <section className="section" id="projects"><div className="container"><div className="cta"><div><h2>لديك مشروع وتبحث عن محترف؟</h2><p className="muted">انشر طلبك مجانًا واستقبل عروضًا من مستقلين جزائريين.</p></div><button className="btn primary">انشر مشروعك الآن</button></div></div></section>
  </main>
  <footer className="footer"><div className="container footerGrid"><div><h3>سوق DZ</h3><p>منصة جزائرية للخدمات والمشاريع والسلع، مصممة للثقة والنمو.</p></div><div><h3>المنصة</h3><a href="#services">الخدمات</a><a href="#projects">المشاريع</a><a href="#products">السلع</a></div><div><h3>للمحترفين</h3><a href="#">أضف خدمة</a><a href="#">طلبات العملاء</a><a href="#">مركز المساعدة</a></div><div><h3>الثقة والأمان</h3><a href="#">سياسة الاستخدام</a><a href="#">الخصوصية</a><a href="#">النزاعات</a></div></div></footer>
</>}
